const mockGames = [
  {
    result: 'loss',
    map: 'nepal',
    mapType: 'control',
    mapImageUrl: 'nepal.png',
    heroes: ['ashe', 'bastion'],
    heroesImageUrl: ['ashe.png', 'bastion.png'],
    date: '01/01/2023',
  },

  {
    result: 'win',
    map: 'new-queen-street',
    mapType: 'push',
    mapImageUrl: 'new-queen-street.png',
    heroes: ['ashe', 'bastion'],
    heroesImageUrl: ['ashe.png', 'bastion.png'],
    date: '01/01/2023',
  },

  {
    result: 'loss',
    map: 'oasis',
    mapType: 'control',
    mapImageUrl: 'oasis.png',
    heroes: ['ashe', 'bastion'],
    heroesImageUrl: ['ashe.png', 'bastion.png'],
    date: '02/01/2023',
  },

  {
    result: 'draw',
    map: 'paraiso',
    mapType: 'hybrid',
    mapImageUrl: 'paraiso.png',
    heroes: ['ashe', 'bastion'],
    heroesImageUrl: ['ashe.png', 'bastion.png'],
    date: '03/03/2023',
  },

  {
    result: 'win',
    map: 'dorado',
    mapType: 'escort',
    mapImageUrl: 'dorado.png',
    heroes: ['cassidy', 'hanzo'],
    heroesImageUrl: ['cassidy.png', 'hanzo.png'],
    date: '11/02/2023',
  },

  {
    result: 'win',
    map: 'nepal',
    mapType: 'control',
    mapImageUrl: 'nepal.png',
    heroes: ['cassidy', 'hanzo'],
    heroesImageUrl: ['cassidy.png', 'hanzo.png'],
    date: '11/02/2023',
  },
  {
    result: 'win',
    map: 'rialto',
    mapType: 'escort',
    mapImageUrl: 'rialto.png',
    heroes: ['cassidy', 'hanzo'],
    heroesImageUrl: ['cassidy.png', 'hanzo.png'],
    date: '13/02/2023',
  },
  {
    result: 'loss',
    map: 'colosseo',
    mapType: 'push',
    mapImageUrl: 'colosseo.png',
    heroes: ['cassidy', 'hanzo'],
    heroesImageUrl: ['cassidy.png', 'hanzo.png'],
    date: '13/02/2023',
  },

  {
    result: 'win',
    map: 'junkertown',
    mapType: 'escort',
    mapImageUrl: 'junkertown.png',
    heroes: ['junker-queen', 'sigma'],
    heroesImageUrl: ['junker-queen.png', 'sigma.png'],
    date: '14/02/2023',
  },
  {
    result: 'loss',
    map: 'busan',
    mapType: 'control',
    mapImageUrl: 'busan.png',
    heroes: ['hanzo', 'sigma'],
    heroesImageUrl: ['hanzo.png', 'sigma.png'],
    date: '14/02/2023',
  },
  {
    result: 'win',
    map: 'esperanca',
    mapType: 'push',
    mapImageUrl: 'esperanca.png',
    heroes: ['junker-queen', 'sigma'],
    heroesImageUrl: ['junker-queen.png', 'sigma.png'],
    date: '14/02/2023',
  },
  {
    result: 'loss',
    map: 'hollywood',
    mapType: 'hybrid',
    mapImageUrl: 'hollywood.png',
    heroes: ['junker-queen', 'sigma'],
    heroesImageUrl: ['junker-queen.png', 'sigma.png'],
    date: '14/02/2023',
  },
  {
    result: 'loss',
    map: 'eichenwalde',
    mapType: 'hybrid',
    mapImageUrl: 'eichenwalde.png',
    heroes: ['junker-queen', 'sigma'],
    heroesImageUrl: ['junker-queen.png', 'sigma.png'],
    date: '15/02/2023',
  },
];

export default mockGames;
